---
title: "Extracting participant characteristics"
author: "Niels Krogsgaard"
date: "12/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
pacman::p_load(tidyverse, readbulk, tuneR)
```

```{r}
df_all <- read_bulk("../Our_data")
```


```{r}
2
```

```{r}
data.frame(df_all$subject_nr, df_all$gender, df_all$age) %>%
  unique() %>% 
  group_by(df_all.gender) %>% 
  summarise(count = n())
```


```{r}
df_all$age <- as.numeric(df_all$age)

#subject_nr 99 (aka. Jonathan) wrote his age as being toogtyve instead of 22
df_all_no99 <- df_all %>% 
  filter(subject_nr != '99')

subject_means <- df_all_no99 %>% 
  group_by(subject_nr) %>% 
  summarise(mean_age = mean(age))
```

```{r}
mean(subject_means$mean_age)
```

```{r}
range(subject_means$mean_age)
```

```{r}
subject_accuracy <- df_all %>% 
  filter(practice != 'yes') %>% 
  group_by(subject_nr) %>% 
  summarise(subject_accuracy = sum(correct)/n(), n_correct = sum(correct), n_total = n())
```


```{r}
mean(subject_accuracy$subject_accuracy)
```

```{r}
df_all %>% 
  filter(practice != 'yes') %>% 
  group_by(subject_nr) %>% 
  summarise(subject_accuracy = sum(correct)/n(), n_correct = sum(correct), n_total = n())
```

```{r}
df_all %>% 
  filter(practice != 'yes') %>% 
  ggplot(aes(x = response_time)) + 
  geom_histogram()
```
```{r}
filter(df_all, response_time > 2000)
```

```{r}
df_all %>% 
  filter(practice != 'yes') %>% 
  group_by(subject_nr) %>% 
  summarise(subject_accuracy = sum(correct)/n(), n_correct = sum(correct), n_total = n(), reaction_time = mean(response_time), Level_of_language = mean(lang))
```

```{r}
print(mean(df_all$lang))
print(range(df_all$lang))
```
```{r}
df_all %>% 
  ggplot(aes(x = factor(subject_nr), y = response_time, fill = factor(subject_nr))) +
  geom_boxplot() +
  stat_summary(fun.y=mean, geom="point", shape=20, size=2, color="red", fill="red")
```

```{r}
#length of sounds
#path of file
sound_length <- c()
sound_names <- c('beaker', 'beetle', 'candle', 'candy', 'carriage', 'carrot', 'cradle', 'crayon', 'dollar', "dolphin", "pickle", "picture", "raccoon", "racket", "towel", "tower")

for (i in sound_names){
  path <- paste('../Our_data/sound_files/', i, '.wav', sep = "")
file_audio_path <- path
#Read Files
train_audio = readWave(file_audio_path)
new_len <- round(length(train_audio@left) / train_audio@samp.rate, 2)
sound_length <- c(sound_length, new_len)
}
```

```{r}
print(mean(sound_length))
print(range(sound_length))
```

