---
title: "sigurd version"
author: "Sigurd Fyhn Sørensen"
date: "12/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# START SPIVEY DATA 

## Packages
```{r}
pacman::p_load(tidyverse, lme4, readbulk)
pacman::p_load(MASS,lme4,GGally,ggpubr, reshape, boot)
pacman::p_load(ellipse, tidyverse, Hmisc, plyr)
pacman::p_load(pROC, devtools, reshape2, mousetrap)
```


```{r}

spivey_df <- read_bulk("/Users/sigurd/OneDrive - Aarhus Universitet/Perception and Action (3rd Semester)/Perception And Action EXAM/Spivey_data_mouse")
```

## Load data 
```{r}
spivey_df_short <- spivey_df %>% 
  dplyr::select(height, width, left_stimuli_1, right_stimuli_1, initiation_time_mouse, time_mouse, timestamps_mouse, sound, practice, timestamps_mouse, xpos_mouse, ypos_mouse, response, response_time, count_trial_sequence, correct_response, correct, subject_nr, trial_type, live_row )

write_csv(spivey_df_short, "mouse_spivey_short.csv")
```


```{r}
#Subset for Accuracy == TRUE.
spivey_df_short_correct <- subset(spivey_df_short, correct == 1)

#TUrn Subject into factor
spivey_df_short_correct$subject_nr <- factor(spivey_df_short_correct$subject_nr)
```


```{r}
print(c(nrow(spivey_df_short_correct)/nrow(spivey_df_short)*100, "% correct"))
```

# Mousetrap
```{r}
m <- mt_import_mousetrap(spivey_df_short_correct)
```

```{r}
mt_plot(data = m , use = "trajectories", color = "trial_type")
```
```{r}
#remap
m <- mt_remap_symmetric(
  m, 
  use = 'trajectories',
  remap_xpos = "left"
  )

mt_plot(
  m, 
  use = 'trajectories',
  color = 'trial_type'
  )
```
```{r}
# plot with timestamps
mt_plot(
  m, 
  x = 'timestamps', # modifying the x-axis to plot timestamps
  y = 'xpos',       # modifying the y-axis to plot the xpos
  use = 'trajectories',
  color = 'trial_type' 
)
```
```{r}
m <- mt_exclude_initiation(m)
mt_plot(
  m, 
  x = 'timestamps',
  y = 'xpos',
  use = 'trajectories',
  color = 'trial_type' 
)
```
```{r}
m <- mt_time_normalize(m, nsteps = 101)
mt_plot(
  m, 
  use = 'tn_trajectories',
  color = 'trial_type'
)
```
```{r}
#Final prep of data.
m <- mt_align(
  m,
  use = "tn_trajectories",
  save_as = "tn_align_trajec",
  dimensions = c("xpos", "ypos"),
  coordinates = "isotropic",
  align_start = TRUE ,
  align_end = TRUE,
  align_side = "no",
  verbose = FALSE
)
```


```{r}
mt_plot_aggregate(
  m, 
  use = 'tn_align_trajec',
  color = 'trial_type'
) + 
  labs(
    title = 'Aggregated time-normalized mouse trajectories')
```

```{r}
#Measures calculated using tn (time normalized and space normalized)
m <- mt_measures(
  m,
  use = 'tn_align_trajec')

#### FIX ### LOOK AT WITH NIELS.
#derivs calculated using tn (time normalized) (we did not space normalize but maybe that is ok)
m <- mt_derivatives(
  m,
  save_as = 'deriv',
  use = "tn_trajectories",
  dimensions = c("xpos", "ypos"),
  timestamps = "timestamps",
  prefix = "",
  absolute = FALSE,
  return_delta_time = FALSE,
  verbose = FALSE
)

#cbind(m$tn_trajectories, m$measures)

as.data.frame(m$deriv)
```
## TENDENCY IN TWO CONDITIONS. 
```{r}

mt_measures_aggre <-  mt_aggregate(
  m,
  use = 'measures',
  #use_variables = c('MAD', 'xpos_flips','AUC', 'RT'), # if you want all of the measures, exclude this line 
  use2_variables = 'trial_type')

mt_measures_aggre
```

### CREATE DATA FRAME WITH NORMALIZED POSITIONS, TIME, VELOCITY AND ACCELERATION. 
Same as normalized_positions for the negation data. 

```{r}
normalized_spivey_df <- cbind(m$data, m$deriv)
write_csv(normalized_spivey_df, "norm_position_spivey.csv")
```

### Prepare data frame for PCA rename colnames to match. 
```{r}
oldnames <- colnames(normalized_spivey_df)[18:ncol(normalized_spivey_df)]

#Time , X , Y , Steps, dist, vel , acc
new_names <- c(paste0("t",sprintf('%0.3d', 1:101)),
  paste0("x",sprintf('%0.3d', 1:101)),
  paste0("y",sprintf('%0.3d', 1:101)),
  paste0("s",sprintf('%0.3d', 1:101)),
  paste0("d",sprintf('%0.3d', 1:101)),
  paste0("v",sprintf('%0.3d', 1:101)),
  paste0("a",sprintf('%0.3d', 1:101)))


pacman::p_load(data.table)


setnames(normalized_spivey_df, old = oldnames, new = new_names)

setnames(normalized_spivey_df, old = c("subject_nr", "live_row", "trial_type", "response"), new = c("Subject", "Item.number", "Polarity", "Response"))



```


## Try and use the pca for prediction (same features as in the original data set for training)
```{r}
all_data_columns_spivey <- names(dplyr::select(normalized_spivey_df,
                                          starts_with("x"),
                                          starts_with("y"),
                                          starts_with("v"),
                                          starts_with("a")))
  

normalized_positions.new.spivey <- normalized_spivey_df %>%
  dplyr::select(Subject, Item.number, Polarity, Response, one_of(all_data_columns_spivey))

write_csv(normalized_positions.new.spivey, "spivey_data_normalized_newnames_subset.csv")


predict(m_pca, normalized_positions.new.spivey)
```


```{r}
# THIS IS NOT USED JUST FOR REFERENCE

##PCA in training set
  m_pca_spivey <- normalized_spivey_df %>%
    dplyr::select(one_of(all_data_columns)) %>%
    as.matrix %>%
    prcomp(center = TRUE, scale = TRUE)
  
  n_pca <<- 13
  normalized_positions_tr_pca <- bind_cols(normalized_spivey_df,
                                           as.data.frame(m_pca$x[,1:n_pca]))


```

